type Query {
  getMessage(
    id: ID
    name: String
    age: Int
    gender: Boolean
    income: Float
    friend: UserInput
  ): [UserInput]
}

input UserInput {
  name: String
  age: Int
  gender: [Boolean]
  banks: Bank
}

input Bank {
  name: [BankName]
  balance: Int
}

type User {
  name: String
  age: Int
  gender: Boolean
}

enum BankName {
  FBL
  HBL
  Meezan
  BAHL
  UBL
}